### ISSUE TITLE
Retrieving Method details.

### ISSUE THREAD

**Issue by hasanbaig** [copasi/basico#11]
Hi, 

I want to retrieve complete information of methods used in any specific task. For example, copasi model with optimization task has the following method details: 

`  <Method name="Genetic Algorithm" type="GeneticAlgorithm">
        <Parameter name="Log Verbosity" type="unsignedInteger" value="0"/>
        <Parameter name="Number of Generations" type="unsignedInteger" value="200"/>
        <Parameter name="Population Size" type="unsignedInteger" value="20"/>
        <Parameter name="Random Number Generator" type="unsignedInteger" value="1"/>
        <Parameter name="Seed" type="unsignedInteger" value="0"/>
        <Parameter name="Mutation Variance" type="float" value="0.10000000000000001"/>
        <Parameter name="Stop after # Stalled Generations" type="unsignedInteger" value="0"/>
      </Method>
`

I want to retrieve/set all the information including the "type" of the method. I tried to use `get_opt_settings()` but i returns on the following information related to method: 
`'method': {'Number of Generations': 200, 'Population Size': 20, 'name': 'Genetic Algorithm'}`

**Comment by fbergmann** [comment]
I'm not entirely sure what you mean by type. In basico, the the method names are used directly to switch the method. So you'd use: 

```
    set_opt_settings({'method': {'name': 'Particle Swarm'}})
```

to switch particle swarm. I added function to the PE class, to convert between names and enumerations, but i dont think you would need that. 

I did add an extra flag `basic_only` to be passed on to the `get_task_settings` function that was used to filter out the advanced parameters. So you can now use: 

```
In [5]: get_opt_settings()
Out[5]:
{'scheduled': False,
 'update_model': False,
 'problem': {'Maximize': False,
  'Randomize Start Values': False,
  'Calculate Statistics': True},
 'method': {'Iteration Limit': 2000,
  'Swarm Size': 50,
  'Std. Deviation': 1e-06,
  'name': 'Particle Swarm'},
 'report': {'filename': '',
  'report_definition': 'Optimization',
  'append': True,
  'confirm_overwrite': True},
 'expression': '',
 'subtask': 'Steady-State'}

```

or

```
In [6]: get_opt_settings(basic_only=False)
Out[6]:
{'scheduled': False,
 'update_model': False,
 'problem': {'Maximize': False,
  'Randomize Start Values': False,
  'Calculate Statistics': True},
 'method': {'Log Verbosity': 0,
  'Iteration Limit': 2000,
  'Swarm Size': 50,
  'Std. Deviation': 1e-06,
  'Random Number Generator': 1,
  'Seed': 0,
  'Stop after # Stalled Iterations': 0,
  'name': 'Particle Swarm'},
 'report': {'filename': '',
  'report_definition': 'Optimization',
  'append': True,
  'confirm_overwrite': True},
 'expression': '',
 'subtask': 'Steady-State'}

```

**Comment by fbergmann** [comment]
the updates have now been released to pypi

**Comment by hasanbaig** [comment]
> I'm not entirely sure what you mean by type. 

by type, I meant to refer the following: 
<Method name="Genetic Algorithm" **type=**"GeneticAlgorithm">

In current CloudCOPASI code, the algorithms are set based on the above "type" attribute. So, now you said that I can only refer to algorithm name rather than "type", so I will go ahead with it. 

Thanks for the release. I will check it out now.

**Comment by fbergmann** [comment]
this issue has been resolved, and is available on pypi
