### ISSUE TITLE
Running Gillespie simulatons

### ISSUE THREAD

**Issue by TorkelE** [copasi/basico#13]
Hello,
I have gotten this to work, however, I have been unable to run Gillespie type simulations. This is possible in Copasi, but there is no mention of it in the basic documentation?

**Comment by fbergmann** [comment]
basico provides access to all the simulation methods that are also present in COPASI. Here is an example document showing how to run a stochastic simulation

<https://basico.readthedocs.io/en/latest/notebooks/Creating_a_simple_model.html>

you just pass the `method` parameter to the `run_time_course` command. Note that just as in the COPASI user interface, please make sure to use realistic units for compartments and species, as the stochastic simulators operate on the particle number.

**Comment by TorkelE** [comment]
thanks for the quick reply!
