### ISSUE TITLE
Increase step size to avoid "CTrajectoryMethod (12): Internal step limit exceeded." error

### ISSUE THREAD

**Issue by TorkelE** [copasi/basico#14]
When I attempt to simulate a large model using
```python
from basico import *
load_model('../Data/mymodel.xml');
run_time_course(duration=1000.0, method='deterministic')
```
(I also seem to get it with `method='directMethod'`

I get an error:
```
ERROR:root:Error while running the simulation: >EXCEPTION 2022-02-15T19:38:40<
  CTrajectoryMethod (12): Internal step limit exceeded.
```

Looking here, I get the impression that I can increase the max step size: http://copasi.org/Support/User_Manual/Methods/Time_Course_Calculation/Hybrid_Simulation/#:~:text=Max%20Internal%20Steps,default%20value%20is%20'1000000'.

However, I am unsure how to do so in basico.

**Comment by fbergmann** [comment]
You could either use automatic step size control:

```python
run_time_course(duration=1000.0, automatic=True, method='deterministic')
```

(which could be very efficient for some models, but very slow for others). Or if you want outputs for a fixed number of steps this would be: 

```python
run_time_course(duration=1000.0, intervals=100, method='deterministic')
```

or of you want to specify, that you want output every 10 steps: 


```python
run_time_course(duration=1000.0, stepsize=10, method='deterministic')
```

(Note these are all only the output steps for which you will get output, the internal step size will be higher (unless automatic is used))

By default on a new or importet model, the number of intervals will default to 100 and the duration to 1. So in your code you only changed the duration, not the number of intervals to return. While in many cases this might be fine, for some models it is not. 

All parameters that can be specified are described under [run_time_course](https://basico.readthedocs.io/en/latest/API/basico.html?highlight=run_time_course#basico.task_timecourse.run_time_course)

**Comment by TorkelE** [comment]
Thanks a lot, that's very helpful :)
