### ISSUE TITLE
Slow ssa simulation of large-ish model

### ISSUE THREAD

**Issue by TorkelE** [copasi/basico#15]
Hi,
I am trying to simulate a sbml model (attached as a .txt file, as GitHub does not accept .XML files). This is the code:
```python
from basico import *
load_model('../Data/egfr_net.txt');
%time run_time_course(duration=0.0001, method='directMethod');
```
the simulation time is about 20s, which is very long considering the short time (0.0001). I have tried setting `automatic=True`, but that does not change the time.

[egfr_net.txt](https://github.com/copasi/basico/files/8098292/egfr_net.txt)

**Comment by shoops** [comment]
That is an absolutely amazingly fast speed. The model has over 3749 reactions. Loading it in less tan 20 second and simulating it with the direct method when the particle number for egf(r) is over 1,000,000 is a great achievement. Note that for a stochastic process automatic will write out each reaction event and thus should only be used for models with few reaction events.

**Comment by TorkelE** [comment]
Thanks for the clarification! Just wanted to check if there was a way to speed it up, but if not it is all good.
