### ISSUE TITLE
Unexpected "ERROR:root:Error while running the simulation: >EXCEPTION 2022-02-22T11:21:58<   CTrajectoryMethod (12): Internal step limit exceeded." when setting large stepsize

### ISSUE THREAD

**Issue by TorkelE** [copasi/basico#16]
Hello,
I have a model which I can simulate without problem using the direct method:
```python
from basico import *
load_model('mymodel.txt');
run_time_course(duration=1000.0, method='directMethod')
```

Next, I want to set `stepsize=1000.0`, to ensure that only the final datapoint is saved:
```python
run_time_course(duration=1000.0, stepsize=1000.0, method='directMethod')
```
however, this gives an error:
```
ERROR:root:Error while running the simulation: >EXCEPTION 2022-02-22T11:21:58<
  CTrajectoryMethod (12): Internal step limit exceeded.
```
and an altered output (final timepoint is around t=775), see image:
![image](https://user-images.githubusercontent.com/18099310/155122729-23024cce-f1e6-4354-b70f-597fcbd62dcc.png)

This seems unexpected to me, as I only change when we save the output, I am uncertain why this causes an error.

Thie file is attached (originally had the .XML extension, but changed to .txt so that GitHub would accept it):
[mymodel.txt](https://github.com/copasi/basico/files/8116199/mymodel.txt)

**Comment by fbergmann** [comment]
By default we use 100 as number of intervals. So in your first call, you have 100 steps each allowing the maximal internal step number of `1000000` (by default)

With a duration of 1000, and a step size of 1000, you are asking COPASI, to just perform the simulation and only return you the output at the end. So in this case the `1000000` internal steps dont suffice for you. It would probably be easier to in python just access the last element of the output returned. 

```python
run_time_course(duration=1000.0, method='directMethod').iloc[[-1]]
```

if you really want to change the number of internal steps, you'd use `set_task_settings` with the same names as they are given in the COPASI user interface (unfortunately the names are different between the individual methods. In this case can you try, setting: 

```python
set_task_settings(
  T.TIME_COURSE, # change the time course task
  {
    'method': 
      {
        'name': 'Stochastic (Direct method)', 
        'Max Internal Steps': 1000000000 
      }
  })
```

For a full list of all parameters you can change that way, you can have a look at `get_task_settings(T.TIME_COURSE)`.

**Comment by TorkelE** [comment]
Thank you,
it seems best just to avoid changing `stepsize`?

**Comment by fbergmann** [comment]
It depends on what you want. If you want just one output interval, then i would specify `intervals=1`. That has the same effect as setting stepsize to the duration, but it captures your intent more readily. But it means that then all the computation has to happen within that one interval. If then the maximal number of internal steps is too big, then this will fail. 

I would use stepsize, to indicate that i care about output every couple of minutes for example (rather than a certain number of intervals). 

But to make things easier, if the normal time course run worked for you, and you are just interested in the last time point, i would  simply grab that one from the data returned, as outlined above.

**Comment by TorkelE** [comment]
Ahh, I think I get it now:
internal steps is the number of steps in between two output data points? So when I set the last point of the simulation as the only datapoint, for a large simulation, that makes loads of steps between outputs, causing the error?

**Comment by fbergmann** [comment]
Exactly!

**Comment by TorkelE** [comment]
Thanks a lot, I get it all now. Very helpful!
