### ISSUE TITLE
File reading error in Parameter Estimation Task.

### ISSUE THREAD

**Issue by hasanbaig** [copasi/basico#20]
Hi,

I am following parameter estimation tutorial (https://basico.readthedocs.io/en/latest/notebooks/Parameter_Estimation_Example.html) and I reached to the step 4 where I run 

```Python
run_parameter_estimation(method='Statistics')
```

but I get the following error: 
```Python
ERROR:root:Error while initializing parameter estimation: >ERROR 2022-04-18T09:47:44<
  CFitting (8): Failure reading file '~/../Tutorials/2017-ICSB/MAPKdata.txt'.
```

I do not have this directory `/Tutorials/2017-ICSB/` on my computer. Do I need to provide the path for this file **MAPKdata.txt** explicitly in `run_paramtere_estimation` function? I tried to look at the list of arguments it takes but I could not see the file path can be specified. Please suggest what I am missing here? 

Thanks

**Comment by pmendes** [comment]
Hasan, that is an "error" in the copasi file I supplied you. This is not a BasiCO bug.

 I forgot to remove the absolute path for the data file. I can edit that and send you a corrected file.

**Comment by hasanbaig** [comment]
Oh ok. Thank. looking forward to receiving it.
