### ISSUE TITLE
Need help with parameter estimation

### ISSUE THREAD

**Issue by hasanbaig** [copasi/basico#21]
Hi,

I am working with parameter estimation. Instead of following the procedure of "scheduling" the PE task to "execute" and running the model using CLI, I noticed in the [basico documentation](https://basico.readthedocs.io/en/latest/notebooks/Parameter_Estimation_Example.html) that I can directly run the parameter estimation task and obtain the solution using the `run_parameter_estimation()` method. I ran this method with the copasi method **Current Solution Statistics** and got the required solution. I now have the following questions: 

1. What is the difference between `run_parameter_estimation()` and `get_parameters_solution()` when they both return the same results (in my case as well as in the documentation)? 

2. I have 3 fit parameters in my model, and I get the solution for all 3 of them when I run above basico method. However, when I run ` get_experiment_data_from_model()`, I do not get the data of relevant parameters. Please suggest if I am missing anything. (Currently I am not in a need of experimental data but asking just out of curiosity)

3. As same as obtaining the solution values of parameters using the above basico method, I am wondering if there is anyway to get the calculated **Objective Value** also?

4. Finally, while creating a report, how can I included the "Objective Value" to go in the report?

Thanks!

**Comment by fbergmann** [comment]
I've created a colab notebook, that answers your questions in detail: 
https://colab.research.google.com/drive/1TrFpePxviJawNAg9LpEMsUvQU_1YPHK9?usp=sharing

TDLR: 
1. get_parameter_solution only returns the result of the last run
2. get_experimental data returns the data set up for the parameter estimation task, not the fit parameters. 
3. the objective value is included in `get_fit_statistics`
4. By using a CN: `CN=Root,Vector=TaskList[Parameter Estimation],Problem=Parameter Estimation,Reference=Best Value`

**Comment by hasanbaig** [comment]
Thanks a lot Frank! 
For point 4, I learned to do that using CopasiUI (using expert mode), however I just wanted to know if there is any alternate available in BasiCO. 

Thanks. It is all helpful and I will close the issue.
