### ISSUE TITLE
AttributeError: 'CDataObject' object has no attribute 'setDblValue' when running plot_per_dependent_variable()

### ISSUE THREAD

**Issue by nicolas-huber** [copasi/basico#22]
Hello basiCO team,

when I'm running the function 'plot_per_dependent_variable()' I get the following error: 

'AttributeError: 'CDataObject' object has no attribute 'setDblValue'' with the following traceback:

(Environment: Anaconda 3; Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]; IPython 7.16.1)

```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-0f3cf678761d> in <module>
----> 1 plot_per_dependent_variable();

C:\anaconda3\lib\site-packages\basico\task_parameterestimation.py in plot_per_dependent_variable(**kwargs)
   1176         return result
   1177
-> 1178     exp_data, sim_data = get_simulation_results(**kwargs)
   1179
   1180     dependent_variables = {}

C:\anaconda3\lib\site-packages\basico\task_parameterestimation.py in get_simulation_results(values_only, **kwargs)
   1027             model.updateInitialValues(change_set)
   1028
-> 1029         _update_fit_parameters_from(dm, solution, exp_name)
   1030
   1031         if experiment.getExperimentType() == COPASI.CTaskEnum.Task_steadyState:

C:\anaconda3\lib\site-packages\basico\task_parameterestimation.py in _update_fit_parameters_from(dm, solution, exp_name)
   1078                 obj.getObjectParent().setInitialConcentration(value)
   1079             elif type(obj.getObjectParent()) is COPASI.CCopasiParameter:
-> 1080                 obj.setDblValue(value)
   1081                 model.updateInitialValues(obj)
   1082             else:

C:\anaconda3\lib\site-packages\COPASI\__init__.py in <lambda>(self, name)
   3235     for _s in [CObjectInterface, CUndoObjectInterface]:
   3236         __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
-> 3237     __getattr__ = lambda self, name: _swig_getattr(self, CDataObject, name)
   3238     __repr__ = _swig_repr
   3239     Container = _COPASI.CDataObject_Container

C:\anaconda3\lib\site-packages\COPASI\__init__.py in _swig_getattr(self, class_type, name)
     83     if method:
     84         return method(self)
---> 85     raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
     86
     87
```

I'm using the example model 'LM' and I'm following the steps of the parameter estimation as listed in the documentation here: https://basico.readthedocs.io/en/latest/notebooks/Parameter_Estimation_Example.html
Input lines 1 - 11 all work without any issue.

**Comment by fbergmann** [comment]
sorry for the inconvenience, can you please send me the output of: 

```python
import basico
import COPASI

print(basico.__version__)
print(COPASI.__version__)

```

thank you

**Comment by fbergmann** [comment]
My suspicion is that you have an older version of the python-copasi package installed. So if you tried running `pip install --upgrade python-copasi` i think the issue might go away. For me the notebook runs fine the current version (4.36.260).

**Comment by nicolas-huber** [comment]
> sorry for the inconvenience, can you please send me the output of:
> 
> ```python
> import basico
> import COPASI
> 
> print(basico.__version__)
> print(COPASI.__version__)
> ```
> 
> thank you

> My suspicion is that you have an older version of the python-copasi package installed. 

The basico version is 0.19 and the python-copasi version was 4.29.227. Your suspicion was absolutely correct, I updated my python-copasi to 4.36.260, and it works now! Thank you very much for the quick and helpful response 👍
