### ISSUE TITLE
Names appear different in  exp_data and sim_data dataframes 

### ISSUE THREAD

**Issue by DeepaMahm** [copasi/basico#24]
Hi @fbergmann ,

Square brackets are missing in the columns names of  `sim_data` returned by the function `get_simulation_results` for time course data.

e.g.
```
sim_data>
Index(['ADP', 'fructose 6-phosphate', 'NAD', 'glyceraldehyde 3-phosphate',
       'pyruvate{cytosol}', 'dihydroxyacetone phosphate', '2-phosphoglycerate',
       dtype='object')

exp_data>
Index(['Time', '[d-glucose{"external compartment (blood)"}]_0', '[ATP]',
       '[dihydroxyacetone phosphate]', '[fructose 6-phosphate]',
       dtype='object')
```

For steady-state data both `sim_data` and `exp_data` have brackets for the concentration of species in the column names.

Could you please have a look?

**Comment by fbergmann** [comment]
i can change the output format, if that would help. So far the results were just returned from the internal time series object, but i can rename them.

**Comment by DeepaMahm** [comment]
Thanks so much, that will be really helpful.

**Comment by fbergmann** [comment]
this has since been released
