### ISSUE TITLE
How to set mass-action rate constant for a reaction?

### ISSUE THREAD

**Issue by stbachinger** [copasi/basico#27]
Hello :) 
How to set mass-action rate constant for a reaction? What is the exact parameter that I give to add_function()?
Thanks! Any help is appreciated :)

**Comment by fbergmann** [comment]
I would not use `add_function` for this, `add_reaction` would be the one to use: 

`add_reaction('R1', 'A -> B') `

would create a reaction R1 with mass action and a local parameter of k1 = 0.1. If you wanted to change that you could use: 

`add_reaction('R1', 'A -> B', mapping={'k1': 2}) `

please let me know if that works for you.

**Comment by stbachinger** [comment]
Yes, this is working! Thank you for the fast response :)
