### ISSUE TITLE
setting a function that requires modifiers, should map them if specified

### ISSUE THREAD

**Issue by fbergmann** [copasi/basico#29]
When changing a function on a reaction, it should automatically add modifiers to the reaction scheme. 

* currently, when a reaction `r1` with scheme `A -> B` is assigned a kinetic using modifiers this fails

In the gui, this is allowed, however, this results in an invalid function, since no mapping is specified at that point. I would rather want to avoid creating invalid states, as it would be hard to track down later. 

So i propose to silently add modifiers to the reaction scheme, iff a mapping for modifier to species is defined. that means:

* `set_reaction('r1', function='function with modifier')` would still fail, however
* `set_reaction('r1', function='function with modifier', mapping={'formulaTokenUsedAsModifier', 'speciesName' })` would work

@pmendes would that work for you?

**Comment by pmendes** [comment]
@fbergmann I think that is the best solution, thanks.

**Comment by fbergmann** [comment]
this has now been released
