### ISSUE TITLE
Conditional Stochastic Events

### ISSUE THREAD

**Issue by fabriciocravo** [copasi/basico#30]
The following code does not trigger an stochastic event once A reaches zero:

new_model(name='Simple Model')
add_reaction('R1', 'A ->')
set_species('A', initial_particle_number=50)
set_reaction_parameters('(R1).k1', value=1)
add_event('E1', 'A == 0', [('A', '50')])

result = run_time_course(duration=20, method='stochastic')
result.plot()
plt.show()

Thank you for your time and reading this report.

**Comment by pmendes** [comment]
That is what should happen. Once A is zero the propensity of the reaction "A ->" is also zero.  (any more reaction events at that point would make A go negative which is impossible)

**Comment by fabriciocravo** [comment]
Hi Pedro Mendes, thank you for your quick reply. 

I understand. However, even in the following two stochastic models bellow where the propensity of the reactions is not zero the event does not trigger. Is this also supposed to happen? I am little confused because it does trigger if I use a deterministic model (last model supplied)

new_model(name='Simple Model')
add_reaction('R1', 'A ->')
set_species('A', initial_particle_number=100)
set_reaction_parameters('(R1).k1', value=1)
add_event('E1', 'A <= 10', [('A', '50')])
result = run_time_course(duration=10, method='stochastic')
result.plot()
plt.show()

new_model(name='Simple Model')
add_reaction('R1', 'A ->')
add_reaction('R2', 'B -> B + C')
set_species('A', initial_particle_number=50)
set_species('B', initial_particle_number=10)
set_species('C', initial_particle_number=0)
set_reaction_parameters('(R1).k1', value=1)
set_reaction_parameters('(R2).k1', value=1)
add_event('E1', 'A <= 10', [('B', '50')])
result = run_time_course(duration=10, method='stochastic')
result.plot()
plt.show()

The deterministic model where the event does trigger: 

new_model(name='Simple Model')
add_reaction('R1', 'A ->')
set_species('A', initial_concentration=100)
set_reaction_parameters('(R1).k1', value=1)
add_event('E1', 'A == 0', [('A', '50')])
result = run_time_course(duration=60)
result.plot()
plt.show()

**Comment by pmendes** [comment]
Oh, I seem to have misunderstood your question; you were asking about the event, not about reactions triggering. Ok I see the issue. Could the problem be that you are specifying the trigger in terms of the concentration of A, rather than the particle number?  
Maybe Frank can give a better answer.

**Comment by shoops** [comment]
There are 2 issues here:

1.  The trigger uses the concentration of A
2.  The assignment uses also the concentration of A (this cannot be avoided)

However there is one simple fix which is always helpful for stochastic simulations which is to the the quantity unit to `#` and the volume of the compartment to `1`. The concentration and particle numbers are numerically identical. 

Setting the quantity unit should be done prior to creating the species or reaction.

**Comment by fbergmann** [comment]
Basically what it boils down to, is that i should create an example for stochastic simulations. There are a couple of things that come together here: 

* `run_time_course` by default returns the concentrations (you'd want to look at particle numbers and thus use the `use_numbers=True`  argument
*  when you have the event expression `A <= 10`, it is testing actually the concentration of A. You'd want to point out that it is the particle number `A.ParticleNumber < 10`
* what might make this easier is if you'd set the substance unit to something else but mol/l, you could do that by adding a `substance_unit='1'` parameter when you create the new model
* finally, even in the COPASI gui, the events do not trigger for the gibson -bruck simulation method, so if you switch over to the direct method all works as it should

sorry for the inconvenience. Here the complete example: 

```python
        import basico
        basico.new_model(name='Simple Model', substance_unit='1')
        basico.add_reaction('R1', 'A ->')
        basico.set_species('A', initial_particle_number=50)
        basico.set_reaction_parameters('(R1).k1', value=1)
        basico.add_event('E1', 'A.ParticleNumber <= 1', [('A.ParticleNumber', '50')])

        result = basico.run_time_course(duration=20, method='directMethod', use_numbers=True)
```

also generally, when you encounter issues like that, it is always helpful to compare with the copasi user interface what happens there, so there you'd run: 

```bash
basico.open_copasi()
```

(thats what i did to look what was going on here)

**Comment by fabriciocravo** [comment]
Thank you very much! There is no inconvenience, copasi and basico are extremely good.
That does solve my problem! However, I think it would be useful for me to say that the event triggered event without the use_numbers=True and the ParticleNumber attribute. For instance, the following model worked:

new_model(name='Simple Model', substance_unit='1')
add_reaction('R1', 'A ->')
set_species('A', initial_particle_number=50)
set_reaction_parameters('(R1).k1', value=1)
add_event('E1', 'A <= 1', [('A', '50')])
result = basico.run_time_course(duration=20, method='directMethod')
result.plot()
plt.show()

**Comment by fbergmann** [comment]
> Thank you very much! There is no inconvenience, copasi and basico are extremely good. That does solve my problem! However, I think it would be useful for me to say that the event triggered event without the use_numbers=True and the ParticleNumber attribute. For instance, the following model worked:
> 
> new_model(name='Simple Model', substance_unit='1') add_reaction('R1', 'A ->') set_species('A', initial_particle_number=50) set_reaction_parameters('(R1).k1', value=1) add_event('E1', 'A <= 1', [('A', '50')]) result = basico.run_time_course(duration=20, method='directMethod') result.plot() plt.show()

for a `substance_unit` of `1` i.e a dimensionless model, the concentration is the same as the particle numbers. that's why this worked. In your original model though 1 mol/l has many, many more particles. 

I'm glad this issue is resolved.
