### ISSUE TITLE
BASICO missing binding for Hybrid Runge Kutta method

### ISSUE THREAD

**Issue by CodeByDrescher** [copasi/basico#33]
See `basico.task_timecourse.__method_name_to_type()`:

Bindings exist for both Hybrid LSODA and RK45, but not Hybrid Runge Kutta.

**Comment by fbergmann** [comment]
I've release version 0.50, that adds the `hybrid` shorthand to indicate use of the hybrid runge kutta method. Thanks for letting me know.
