### ISSUE TITLE
installing basico 0.53 on remote ubuntu server via workflow

### ISSUE THREAD

**Issue by lilijap** [copasi/basico#38]
Dear Frank,
I am implementing basio in other repository and I want to use it for different projects, however, I have an issue with installing copasi-basico on a remote ubuntu/macos server.
Maybe you have some hints what to do to avoid this error?

Here is an error message I keep getting (wheel is installed). 

![image](https://github.com/copasi/basico/assets/43205236/5bc50400-882f-4862-bbb4-365cf8cf7310)

**Comment by fbergmann** [comment]
This indicates that the old version of versioneer is not compatible with python 3.12. I've committed a fix earlier this week. Could you try if installing directly from git solves this issue for you: 

```bash
pip install git+https://github.com/copasi/basico.git
```

thanks

**Comment by lilijap** [comment]
Hi Frank,

This solved the problem, thanks!

Have a good day,
Lilija

**Comment by lilijap** [comment]
Closing the issue here.

**Comment by fbergmann** [comment]
i also released a new version 0.54, that resolves the issue when just installing with `pip install copasi-basico`.

**Comment by lilijap** [comment]
Great, thank you! That is very useful.
