### ISSUE TITLE
Error running parameter estimation task

### ISSUE THREAD

**Issue by lilijap** [copasi/basico#39]
Hi Frank,

I tried to reproduce experiments in the notebook "Setting up  parameter Estimation" [https://github.com/copasi/basico/blob/master/docs/notebooks/Setting_up_Parameter_Estimation.ipynb]. However, if I add parameter set to the model with

 `add_parameter_set('InitialState')`

after loading the model, I encountered this error message 

`Error while initializing parameter estimation: `

and the parameter estimation will not produce any result. Why is this so?
What does this error message try to say?

Thanks!

**Comment by fbergmann** [comment]
Took a while to find this one. I'll release a new version for this.

**Comment by lilijap** [comment]
Hi Frank! Thank you for taking care of this!

**Comment by lilijap** [comment]
I just observed the same issue, when running a parameter estimation task just after setting up a sensitivity task. I this case I get the same error also with the newly released basico version.

**Comment by fbergmann** [comment]
Can you describe what ` setting up a sensitivity task` means?

**Comment by lilijap** [comment]
I cannot reproduce this error anymore, sorry for reviving the issue. :)
Thanks!
