### ISSUE TITLE
problems with get_events(), spurious spaces in trigger expression

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#43]
I use 
`mevents = get_events()`
then I inspect the trigger on that:
`mevents.loc['e1','trigger']` and I get 
`'Y.Rate < 0 & & [Y] > 1e - 3'`
but instead it should be 
`'Y.Rate < 0 && [Y] > 1e-3'`
note the spurious spaces between '& &' and in '1e - 3'
of course if I use this string to set another trigger it won't work as the expression is incorrect.

Am I doing something wrong? Where do these extra spaces come from?

**Comment by fbergmann** [comment]
Good find, fixed with release 0.64

**Comment by pmendes** [comment]
the fix solved my issue
