### ISSUE TITLE
Mapping bug for multiple experiments in parameter estimation

### ISSUE THREAD

**Issue by Theo-BRN** [copasi/basico#45]
Heya Frank, hope you're well!

I found evidence of a possible bug when adding experiments for parameter estimation. I may well be running the code wrong somehow, so would be delighted if you could correct it for me!

The bug arises when I try add multiple experiments to COPASI and when I try map a column in those experiments to a global quantity parameter. Then, when trying to get the experimental mapping it gives me a pandas dataframe error: `KeyError: "None of ['column'] are in the columns"`, resulting from the last line of the `get_experiment_mapping` function: `return pandas.DataFrame(data=rows).set_index('column')`. I've attached a notebook, model and experimental data for this in the zip folder.

From some rudimentary digging myself, I think there's something wrong with the experiment object. However, I can't see any difference between when `add_experiment` does work and when it doesn't.

Interestingly
- the .txt files are created fine for all experiments
- it works if you map to a species instead of a parameter/global quantity
- the first experiment is retrieved fine, but the next ones have a problem

Let me know if you want any more detail!
Thanks,
Theo

[PE_Bug.zip](https://github.com/copasi/basico/files/14792567/PE_Bug.zip)

**Comment by fbergmann** [comment]
Thanks for letting me know, this is indeed odd. Especially, that once you save the model after adding the experiment, and open that file in the COPASI UI, you'll find all the data mapped correctly. And indeed, if the test is then simplified, to just load the data and go through the experiments in basico, the experiments 2 and 3 appear to have no mapping.

**Comment by Theo-BRN** [comment]
Yes exactly! Glad it's not just me!

**Comment by Theo-BRN** [comment]
Thanks Frank! It looks like those changes work for me now too. Out of curiosity, when will the pip install version be updated with these changes? Is it best practice to wait for more changes before updating that? Or do you foresee a problem with the current version?

**Comment by fbergmann** [comment]
Hello Theo, the short answer is soon .. definitely within a day or so. While that issue is being fixed, I'll also try to address some incompatibilities with different COPASI versions. But I'm almost there. The release will be out tomorrow Saturday at the latest.

**Comment by Theo-BRN** [comment]
Thank you! Didn't mean to rush you, was just curious! Thanks for your quick response :-)

**Comment by fbergmann** [comment]
The release is out now, and solves the issue for creating experiments directly after modifying the model structure.
