### ISSUE TITLE
Cannot find pure Python Wheel for python-copasi package from PyPI

### ISSUE THREAD

**Issue by julien-rudmann** [copasi/basico#48]
Good evening,

I am currently working on a `PyScript` project that I would like to interface with `copasi-basico`.

However, it does not work at the moment because a pure Python wheel image is missing on PyPi : https://pypi.org/project/python-copasi/#files 
according to the following error message (the file should end with `*py3-none-any.whl`) : 
```
Uncaught (in promise) PythonError: Traceback (most recent call last):
File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 146, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'python-copasi'
```
which also redirect to https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package

Unfortunately I can not generate it locally myself, as PyScript does not allow me to change the source for packages.

Would it be possible to generate the pure wheel image for the `python-copasi` package ?

**Comment by fbergmann** [comment]
python-copasi is just the regular COPASI project, wrapped to work with python. So it is not possible to make a pure python wheel for it. That being said, I have been working on cross compiling `python-copasi` to work with pyodide (which is also used by pyscript). Currently not possible to host those files on pypi. 

if you tell me the emscripten version of your pyscript: 

```python
    import sysconfig
    sysconfig.get_platform()
```

I can tell you which wheel to install. It will be one of the two: 

* <http://bqfrank.spdns.org/Files/python_copasi-4.43.288-cp311-cp311-emscripten_3_1_45_wasm32.whl> or
* <http://bqfrank.spdns.org/Files/python_copasi-4.43.288-cp311-cp311-emscripten_3_1_46_wasm32.whl>

**Comment by julien-rudmann** [comment]
Good morning,

The command returns `emscripten-3.1.45-wasm32`, which I guess means I should use the first file (which I have downloaded now). Now trying to point PyScript to this ! 

Thanks !

**Comment by fbergmann** [comment]
Before, i was just adding it to the pyscript.toml file, however that stopped working since i've done it some months ago. Importing it straight in the HTML still seems to work tho: 

<https://pyscript.com/@frank_bergmann/loadinhtml/>

**Comment by julien-rudmann** [comment]
I put it directly in my project for the moment and load it from local with : 
```
    "packages": [
        "./libs/python_copasi-4.43.288-cp311-cp311-emscripten_3_1_45_wasm32.whl",
        "copasi-basico"
    ]
```

I will keep this in mind though if at some point I share it with some colleagues.

Thanks for all your help !
