### ISSUE TITLE
get_compartments() returns a type incompatible with set_compartments()

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#49]
when trying to set_compartment() with values copied from a previous call to get_compartments() I get this error:
`TypeError: in method 'CCompartment_setDimensionality', argument 2 of type 'unsigned int'`
the error goes away when I cast the variable in question to be an int. It seems that for _dimensionality_ get_compartments() returns an _unsigned int_ but for set_compartments() it needs an _int_

**Comment by fbergmann** [comment]
The issue was, that the integer in the data frame is a `numpy.int64` rather than an `int`. I'll release a new version that fixes the issue. In general for your tool I would recommend working with dictionaries (that would have worked before the fix): 

```python
# retrieve info as dictionary
v = as_dict(get_compartments('v', exact=True))
# make changes that need to be made to the dictionary then apply with
set_compartments(exact=True, **v)

```

**Comment by fbergmann** [comment]
i've released an updated package to solve the issue.

**Comment by pmendes** [comment]
Thank you!
