### ISSUE TITLE
Multiple fit_items without all having 'affected'

### ISSUE THREAD

**Issue by Theo-BRN** [copasi/basico#51]
Heya Frank,
I stumbled across this while trying to implement parameter estimation for shared and non-shared experiments. 

When I run something like: 

```
fit_items = [
    {'name': "Values[k_on]", 'lower': 1e05, 'upper': 1e09, 'affected': [exp_name]},
    {"name": "Values[k_off]", 'lower': 1e-05, 'upper': 1e04}
]

bsc.set_fit_parameters(fit_items)
```
It happens whenever the 'affected' key is present in one but not all of the `fit_items` dictionaries. Then I get a type error: `TypeError: 'float' object is not iterable`. 

I think this happens because when `_set_fit_item` function tries to iterate through the `affected` variable but the 'affected' is actually a NaN value, so seen as a float in the error. I think this may happen because pandas fills in blanks as NaN with line 757 in the `set_fit_parameters` function: `fit_parameters = pandas.DataFrame(data=fit_parameters)`. Hope any of that is helpful. 

Otherwise, it's a pretty avoidable I think as I can just put an empty list probably.

Thanks,
Theo

**Comment by fbergmann** [comment]
release 0.67 ignores nan values in there and is now available on pypi. Thanks again for reporting.
