### ISSUE TITLE
if expressions returned incorrectly

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#52]
I noticed parsing this sbml model: [BIOMD0000000429_url.xml](https://www.ebi.ac.uk/biomodels/services/download/get-files/MODEL1209110001/2/BIOMD0000000429_url.xml)
 that Basico returns expressions containing `if` statements incorrectly:

In the model there is an expression for  global quantity "Turgor" which Basico currently returns as:
`if ( Compartments[V].Volume Values[VP_0] Values[eps] * log ( Compartments[V].Volume / Values[VP_0] ) ,0 )`

instead of the correct string:
`if( Compartments[V].Volume gt Values[VP_0] , Values[eps] * log( Compartments[V].Volume / Values[VP_0] ) , 0 )`
notice that the string returned does not contain the `gt` and `,` needed in the if statement

**Comment by fbergmann** [comment]
this is fixed in the release from this morning.
