### ISSUE TITLE
is it possible to get notes or annotations of reactions and events?

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#53]
I'm able to get notes for most model elements using get_notes() but this does not seem to work for reactions. For a reaction called 'R1' I tried with names such as 'R1', 'Reactions[R1]' , 'Reactions(R1)' or 'Reactions.R1' but none seem to work . I also tried passing element=el where el is the object retrieved with get_reaction().  The same happens to events. Is this not supported?

**Comment by fbergmann** [comment]
it should have worked, with the name. As I just pass that to the C++ API and retrieve the object by display name. However, testing this right now this is not working. I'll release a new version that solves the issue.

**Comment by fbergmann** [comment]
I've released a new version that fixes the issue. So it should work like this: 

```python
notes = get_notes(name='r0')
```

where `r0` is a reaction / event or anything really.

**Comment by pmendes** [comment]
Thanks! You are a star!
