### ISSUE TITLE
issue with set_reaction_mapping() when mappings are mixed to global quantities and values

### ISSUE THREAD

**Issue by pmendes** [copasi/basico#56]
I've noticed that set_reaction_mapping() fails when it there is a mix of mappings to global quantities and values:

I have this dictionary for one reaction
`{'substrate': 'Ca_1', 'Shalve': 'K_ER_1', 'V': 'v_ER_1', 'h': 2.0}`
note that h is mapped to a value, but the other parameters are mapped to global quantities. After setting it and then getting it again this is what comes back:
`{'substrate': 'Ca_1', 'Shalve': 0.1, 'V': 0.1, 'h': 0.1}`
all the parameters were  set to the default parameter value...

Note that the mapping I'm trying to set has been obtained from another reaction in an existing copasi model.  If in the original model I change `h` to map to a global quantity `hillcoeff`, then they all get set correctly:
`{'substrate': 'Ca_1', 'Shalve': 'K_ER_1', 'V': 'v_ER_1', 'h': 'hillcoeff'}`
and then I get it back as:
`{'substrate': 'Ca_1', 'Shalve': 'K_ER_1', 'V': 'v_ER_1', 'h': 'hillcoeff'}`

This looks like it is a bug?

**Comment by pmendes** [comment]
btw, this happens both with `set_reaction_mapping()` and with `add_reaction()`

**Comment by fbergmann** [comment]
This indeed looks like a bug thank you for filing it... I'm unfortunately traveling with dodgy internet right now, so I'll get to fix it by Wednesday at the latest. It would make it easier for me if I had the function too, is it just the standard hill `V*(substrate/Shalve)^h/(1+(substrate/Shalve)^h)`. thx

and I hope that add_reaction would be calling set_reaction_mapping, so it would be expected that the same problem arrises for both. 

I get back to you next week.

**Comment by pmendes** [comment]
yes, in this case it is the predefined Hill function.

**Comment by fbergmann** [comment]
This is now fixed in release 0.70

**Comment by pmendes** [comment]
Fix confirmed, thanks!
