### ISSUE TITLE
Retrieving "Time-Course" Task information

### ISSUE THREAD

**Issue by hasanbaig** [copasi/basico#7]
Hi,
I want to retrieve attributes and values related to "Time-Course" task. For example, from the following task section, how can I read the information about "Method" name? 
```
............ 
<Task key="Task_18" name="Time-Course" type="timeCourse" scheduled="false" updateModel="false">
      <Report reference="Report_12" target="" append="1" confirmOverwrite="1"/>
      <Problem>
        <Parameter name="AutomaticStepSize" type="bool" value="0"/>
        <Parameter name="StepNumber" type="unsignedInteger" value="2000"/>
        <Parameter name="StepSize" type="float" value="0.10000000000000001"/>
        <Parameter name="Duration" type="float" value="200"/>
        <Parameter name="TimeSeriesRequested" type="bool" value="1"/>
        <Parameter name="OutputStartTime" type="float" value="0"/>
        <Parameter name="Output Event" type="bool" value="0"/>
        <Parameter name="Start in Steady State" type="bool" value="0"/>
        <Parameter name="Use Values" type="bool" value="0"/>
        <Parameter name="Values" type="string" value=""/>
      </Problem>
      <Method name="Stochastic (Direct method)" type="Stochastic">
        <Parameter name="Max Internal Steps" type="integer" value="1000000"/>
        <Parameter name="Use Random Seed" type="bool" value="0"/>
        <Parameter name="Random Seed" type="unsignedInteger" value="1"/>
      </Method>
    </Task>
............ 
```
If no method currently exists to retrieve "Time-Course" task information, can methods similar to "get_scan_items()" and "get_scan_settings()" be added?

**Comment by fbergmann** [comment]
You'd be using `get_task_settings` for that:

    
    In [1]: from basico import *
    
    In [2]: load_example('bruss')
    Out[2]: <CDataModel "Root">
    
    In [3]: get_task_settings(T.TIME_COURSE)
    Out[3]:
    {'scheduled': False,
     'update_model': False,
     'problem': {'AutomaticStepSize': False,
      'StepNumber': 200,
      'StepSize': 0.5,
      'Duration': 100.0,
      'TimeSeriesRequested': True,
      'OutputStartTime': 2.0,
      'Output Event': False,
      'Start in Steady State': False,
      'Use Values': False,
      'Values': '',
      'Continue on Simultaneous Events': False},
     'method': {'Integrate Reduced Model': True,
      'Relative Tolerance': 1e-06,
      'Absolute Tolerance': 1e-12,
      'Max Internal Steps': 10000,
      'Max Internal Step Size': 0.0,
      'name': 'Deterministic (LSODA)'},
     'report': {'filename': '',
      'report_definition': 'Time-Course',
      'append': True,
      'confirm_overwrite': True}}

**Comment by hasanbaig** [comment]
Okay. Got it. Thanks! I am closing the issue.
